import type { ViewFields } from './types';

export const COUNTRY_DATA_KEYS = [
  'year',
  'cement_co2',
  'cumulative_cement_co2',
  'population',
  'cement_co2_per_capita',
  'co2',
  'co2_growth_abs',
  'co2_growth_prct',
  'co2_including_luc',
  'co2_including_luc_growth_abs',
  'co2_including_luc_growth_prct',
  'co2_including_luc_per_capita',
  'co2_per_capita',
  'coal_co2',
  'coal_co2_per_capita',
  'cumulative_co2',
  'cumulative_co2_including_luc',
  'cumulative_coal_co2',
  'cumulative_flaring_co2',
  'cumulative_gas_co2',
  'cumulative_luc_co2',
  'cumulative_oil_co2',
  'flaring_co2',
  'flaring_co2_per_capita',
  'gas_co2',
  'gas_co2_per_capita',
  'ghg_excluding_lucf_per_capita',
  'ghg_per_capita',
  'land_use_change_co2',
  'land_use_change_co2_per_capita',
  'methane',
  'methane_per_capita',
  'nitrous_oxide',
  'nitrous_oxide_per_capita',
  'oil_co2',
  'oil_co2_per_capita',
  'share_global_cement_co2',
  'share_global_co2',
  'share_global_co2_including_luc',
  'share_global_coal_co2',
  'share_global_cumulative_cement_co2',
  'share_global_cumulative_co2',
  'share_global_cumulative_co2_including_luc',
  'share_global_cumulative_coal_co2',
  'share_global_cumulative_flaring_co2',
  'share_global_cumulative_gas_co2',
  'share_global_cumulative_luc_co2',
  'share_global_cumulative_oil_co2',
  'share_global_flaring_co2',
  'share_global_gas_co2',
  'share_global_luc_co2',
  'share_global_oil_co2',
  'share_of_temperature_change_from_ghg',
  'temperature_change_from_ch4',
  'temperature_change_from_co2',
  'temperature_change_from_ghg',
  'temperature_change_from_n2o',
  'total_ghg',
  'total_ghg_excluding_lucf',
] as const;

export const DEFAULT_COLUMNS = [
  'year',
  'population',
  'co2',
  'cement_co2_per_capita',
] as ViewFields;

export const SORT_COUNTIES = [
  'Country (A-Z)',
  'Country (Z-A)',
  'Population (ASD)',
  'Population (DESC)',
] as const;
